"""empty message

Revision ID: 0058cbcaf3c2
Revises: 592be0e03ac9
Create Date: 2020-08-22 21:53:11.184479

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0058cbcaf3c2'
down_revision = '592be0e03ac9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('unit_master', sa.Column('closing_date', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('unit_master', 'closing_date')
    # ### end Alembic commands ###
