"""empty message

Revision ID: 2dd91e382b7c
Revises: 0058cbcaf3c2
Create Date: 2020-08-26 20:18:24.931644

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2dd91e382b7c'
down_revision = '0058cbcaf3c2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('employee_master', 'mobile',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('unit_master', 'phone',
               existing_type=sa.INTEGER(),
               nullable=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('unit_master', 'phone',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('employee_master', 'mobile',
               existing_type=sa.INTEGER(),
               nullable=True)
    # ### end Alembic commands ###
