"""empty message

Revision ID: 592be0e03ac9
Revises: 1d8cce3b369d
Create Date: 2020-08-22 21:45:14.412941

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '592be0e03ac9'
down_revision = '1d8cce3b369d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('employee_master', sa.Column('birth_date', sa.DateTime(), nullable=True))
    op.add_column('employee_master', sa.Column('designation', sa.String(length=20), nullable=True))
    op.add_column('employee_master', sa.Column('gender', sa.String(length=20), nullable=False))
    op.add_column('employee_master', sa.Column('middle_name', sa.String(length=20), nullable=True))
    op.add_column('employee_master', sa.Column('mobile', sa.Integer(), nullable=True))
    op.add_column('employee_master', sa.Column('photo_id', sa.LargeBinary(), nullable=True))
    op.add_column('employee_master', sa.Column('photo_id_no', sa.String(length=20), nullable=True))
    op.drop_column('employee_master', 'salary')
    op.add_column('unit_master', sa.Column('phone', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('unit_master', 'phone')
    op.add_column('employee_master', sa.Column('salary', postgresql.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True))
    op.drop_column('employee_master', 'photo_id_no')
    op.drop_column('employee_master', 'photo_id')
    op.drop_column('employee_master', 'mobile')
    op.drop_column('employee_master', 'middle_name')
    op.drop_column('employee_master', 'gender')
    op.drop_column('employee_master', 'designation')
    op.drop_column('employee_master', 'birth_date')
    # ### end Alembic commands ###
