"""empty message

Revision ID: ecf0fcbfb21d
Revises: 
Create Date: 2020-08-12 13:15:01.686665

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ecf0fcbfb21d'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('unit_master',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('unit_name', sa.String(length=50), nullable=False),
    sa.Column('address', sa.String(length=355), nullable=True),
    sa.Column('starting_date', sa.DateTime(), nullable=True),
    sa.Column('description', sa.String(length=355), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('employee_master',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('first_name', sa.String(length=20), nullable=False),
    sa.Column('last_name', sa.String(length=20), nullable=False),
    sa.Column('address', sa.String(length=355), nullable=True),
    sa.Column('unit_id', sa.Integer(), nullable=False),
    sa.Column('joining_date', sa.DateTime(), nullable=True),
    sa.Column('leaving_date', sa.DateTime(), nullable=True),
    sa.Column('salary', sa.Float(), nullable=True),
    sa.ForeignKeyConstraint(['unit_id'], ['unit_master.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('employee_master')
    op.drop_table('unit_master')
    # ### end Alembic commands ###
