"""empty message

Revision ID: f79d5c827c9b
Revises: 2dd91e382b7c
Create Date: 2020-08-27 11:05:18.552887

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f79d5c827c9b'
down_revision = '2dd91e382b7c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('employee_master', sa.Column('is_active', sa.Boolean(), nullable=True))
    op.drop_column('employee_master', 'is_working')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('employee_master', sa.Column('is_working', sa.BOOLEAN(), autoincrement=False, nullable=True))
    op.drop_column('employee_master', 'is_active')
    # ### end Alembic commands ###
